name: MartinHH
markdown: kramdown
pygments: true
safe: true
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      author: "Martin"